<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xll.frame.starter</groupId>
        <artifactId>xll-frame-admin</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../../../pom.xml</relativePath>
    </parent>

    <artifactId>xll-frame-system-srv</artifactId>
    <description>基础系统 服务层</description>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- ### 打包配置相关 ### -->
        <!-- 启动类 -->
        <main-class>com.xll.frame.system.srv.FrameAdminApplication</main-class>
        <!-- 程序 jar 输出目录 -->
        <bin-path>bin/</bin-path>
        <!-- 配置文件输出目录 -->
        <config-path>config/</config-path>
        <!-- 依赖 jar 输出目录 -->
        <lib-path>lib/</lib-path>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.xll.frame.starter</groupId>
            <artifactId>xll-frame-system-application</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <!-- ContiNew Starter 日志模块 - 拦截器版（Spring Boot Actuator HttpTrace 增强版） -->
        <dependency>
            <groupId>com.xll.frame.starter</groupId>
            <artifactId>xll-frame-starter-log-interceptor</artifactId>
        </dependency>

        <!-- Liquibase（用于管理数据库版本，跟踪、管理和应用数据库变化） -->
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <!-- 设置构建的 jar 包名 -->
        <finalName>${project.parent.name}</finalName>
        <plugins>
            <!-- Maven 打包插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <!-- 排除配置文件 -->
                    <excludes>
                        <exclude>${config-path}</exclude>
                        <exclude>db/</exclude>
                        <exclude>templates/</exclude>
                        <exclude>logback-spring.xml</exclude>
                    </excludes>
                    <archive>
                        <manifest>
                            <mainClass>${main-class}</mainClass>
                            <!-- 为 MANIFEST.MF 中的 Class-Path 加入依赖 jar 目录前缀 -->
                            <classpathPrefix>../${lib-path}</classpathPrefix>
                            <addClasspath>true</addClasspath>
                            <!-- jar 包不包含唯一版本标识 -->
                            <useUniqueVersions>false</useUniqueVersions>
                        </manifest>
                        <manifestEntries>
                            <!--为 MANIFEST.MF 中的 Class-Path 加入配置文件目录前缀 -->
                            <Class-Path>../${config-path}</Class-Path>
                        </manifestEntries>
                    </archive>
                    <outputDirectory>${project.build.directory}/app/${bin-path}</outputDirectory>
                </configuration>
            </plugin>
            <!-- 拷贝依赖 jar -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/app/${lib-path}</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- 拷贝配置文件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>src/main/resources/${config-path}</directory>
                                </resource>
                                <resource>
                                    <directory>src/main/resources</directory>
                                    <includes>
                                        <include>db/</include>
                                        <include>templates/</include>
                                        <include>logback-spring.xml</include>
                                    </includes>
                                </resource>
                            </resources>
                            <outputDirectory>${project.build.directory}/app/${config-path}</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>