<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xll.frame.starter</groupId>
        <artifactId>xll-frame-starter</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>xll-frame-starter-extension-crud</artifactId>
    <description>Frame Starter 扩展模块 - CRUD（增删改查） - 核心模块</description>
    <packaging>pom</packaging>
    <modules>
        <module>xll-frame-starter-extension-crud-core</module>
        <module>xll-frame-starter-extension-crud-mp</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>